enableGlobalCache: false

pnpEnableEsmLoader: true

packageExtensions:
  '@smithy/middleware-retry@*':
    dependencies:
      '@smithy/node-config-provider': '*'
  '@smithy/config-resolver@*':
    dependencies:
      '@smithy/node-config-provider': '*'
  '@smithy/util-retry@*':
    dependencies:
      '@smithy/types': '*'
  '@mikro-orm/knex@*':
    dependencies:
      '@mikro-orm/entity-generator': '*'
      '@mikro-orm/migrations': '*'
  '@mikro-orm/postgresql@*':
    dependencies:
      '@mikro-orm/core': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      ioredis: '*'
      kafkajs: '*'
  '@monstrs/protobuf-rpc@*':
    dependencies:
      '@bufbuild/protobuf': '*'
  testcontainers@*:
    dependencies:
      '@types/dockerode': '*'
  knex@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      tedious: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
